# Generated by Django 4.0 on 2021-12-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
            ],
        ),
    ]
